### ISSUE TITLE
Request for Working Example of QUIC with ICE

### ISSUE THREAD

**Issue by minchopm** [marten-seemann/draft-seemann-quic-nat-traversal#28]
Hello,

I've been reviewing your draft on QUIC's ability to traverse NATs using ICE as outlined in the draft-seemann-quic-nat-traversal. The concepts and methods introduced, especially the dual mode of operation—using both a standalone ICE process and a QUIC-based signalling channel—are particularly intriguing.

I am currently trying to implement these ideas in a practical setting, but I am encountering some challenges in visualizing how the integration works in real-world applications. It would be tremendously helpful if you could provide a working example or a more detailed guide that demonstrates QUIC working in conjunction with ICE for NAT traversal.

An example implementation or even pseudocode or real solution would greatly aid in understanding the flow and interactions better, and also help in adopting this technique for projects that might benefit from such a setup.

Thank you for your efforts in creating this draft and for considering this request.

Best regards,
Mincho

**Comment by marten-seemann** [comment]
This is the repo of the draft, not an implementation. Feel free to implement one if you’re interested in this.
